/* CREATE TABLE profiles (
id VARCHAR(255) NOT NULL,
name VARCHAR(255) NOT NULL,
email VARCHAR(255),
picture VARCHAR(255),
PRIMARY KEY(id)
); */

/* CREATE TABLE blogs (
id INT NOT NULL AUTO_INCREMENT,
title VARCHAR(255),
body VARCHAR(255),
imgUrl VARCHAR(255),
published TINYINT DEFAULT 0,
creatorId VARCHAR(255),
PRIMARY KEY(id),
FOREIGN KEY(creatorId)
REFERENCES profiles(id)
); */

/* CREATE TABLE comments (
id INT NOT NULL AUTO_INCREMENT,
creatorId VARCHAR(255),
body VARCHAR(255),
blog VARCHAR(255),
PRIMARY KEY(id),
FOREIGN KEY(creatorId)
REFERENCES profiles(id)
); */

